name: kirana_tanjung
description: Kirana Tanjung Management Dashboard.
version: 1.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  http: ^1.1.0
  url_launcher: ^6.2.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.4.1
  pdf: ^3.10.0
  printing: ^5.11.0
  package_info_plus: ^8.0.0
  flutter_markdown: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "web/favicon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "web/favicon.png"
    background_color: "#ffffff"
    theme_color: "#1769FF"

flutter_native_splash:
  color: "#F7F9FC"
  image: "web/favicon.png"
  android_12:
    image: "web/favicon.png"
    color: "#F7F9FC"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - web/favicon.png
